# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: GPTSmartSearch Apps Deployment

on:
  push:
    branches:
      - github-actions-apps
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Set environment for branch
        run: |
          if [[ $GITHUB_REF_NAME == 'refs/heads/main' ]]; then
              echo "DEPLOY_ENVIRONMENT=Development" >> "$GITHUB_ENV"
          elseif [[ $GITHUB_REF_NAME == 'refs/heads/develop' ]]; then
              echo "DEPLOY_ENVIRONMENT=Development" >> "$GITHUB_ENV"
          elseif [[ $GITHUB_REF_NAME == 'refs/heads/release' ]]; then
               echo "DEPLOY_ENVIRONMENT=Development" >> "$GITHUB_ENV"
          else
              echo "DEPLOY_ENVIRONMENT=Development" >> "$GITHUB_ENV"
          fi
          echo "Setting deploying enviroment to [${{ env.DEPLOY_ENVIRONMENT }}]"
      - name: merge backend and common folder 
        run: |
          
          mkdir -p ./target/backend
          cp -r ./apps/backend ./target
          cp -r ./common/*.* ./target/backend

      - name: Create and start virtual environment in backend folder
        run: |
          python -m venv ./target/backend/venv
          source ./target/backend/venv/bin/activate
      
      - name: Install backend dependencies
        run: pip install -r ./target/backend/requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-backend-app
          path: |
            ./target/backend
            !./target/backend/venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ env.DEPLOY_ENVIRONMENT }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-backend-app
          path: .
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          #slot-name: 'dev'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
